# https://taskfile.dev

version: "3"

vars: {}

tasks:
  list:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task --list-all
    silent: true

  remove_system_files:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - find . -name ".DS_Store" -type f -delete -print
      - find . -name "core" -type f -delete -print
    silent: true

  init:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      # remove system files
      - task remove_system_files
      # キャッシュクリア (skillsの読み込み時にcacheが悪さすることが多い)
      - rm -rf ./.devcontainer/.state/claude/plugins/cache/*
      # uv
      - task uv_sync
    silent: false

  fmt:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - treefmt -vv
    silent: false

  uv_sync:
    dir: "{{ .TASKFILE_DIR }}/apps/"
    cmds:
      - uv sync --link-mode=copy --frozen
      # - export PLAYWRIGHT_BROWSERS_PATH=/tmp/ms-playwright
      - uv run python -m playwright install chromium
    silent: true

  genereta_screenshot:
    dir: "{{ .TASKFILE_DIR }}/apps/"
    cmds:
      - task uv_sync
      - uv run src/capture_screenshot.py --output ../contributions.png
    silent: true

