name: Capture screenshot

on:
  # 毎週月曜日9時(JST)に実行
  schedule:
    - cron: "0 0 * * 1" # UTC
  # webから実行
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aazw/github_planter_capture_screenshot:latest
      options: --user root
      env:
        HOME: /root
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - run: capture-screenshot
      - name: Commit and push changes if needed
        shell: bash
        run: |
          # Git設定
          git config --global --add safe.directory /__w/github-planter/github-planter
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 変更があればコミット・プッシュ
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add -A
            git commit -m "new contributions.png"
            git push origin HEAD
          fi
