name: Capture screenshot

on:
  # 毎週月曜日9時(JST)に実行
  schedule:
    - cron: "0 0 * * 1" # UTC
  # webから実行
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install packages
        working-directory: apps
        run: uv sync --link-mode=copy
      - name: Capture Screenshot
        working-directory: apps
        run: uv run src/capture_screenshot.py --output ../contributions.png
      - name: Commit and push changes if needed
        shell: bash
        run: |
          # Git設定
          git config --global --add safe.directory /__w/github-planter/github-planter
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 変更があればコミット・プッシュ
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add -A
            git commit -m "new contributions.png"
            git push origin HEAD
          fi
