# This is a basic workflow to help you get started with Actions

name: planting

# Controls when the workflow will run
on:
  # Cron job
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "planting"
  planting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Repeat changes and commits
        run: |
          # Git のユーザー情報設定
          git config user.name  "aazw"
          git config user.email "3594744+aazw@users.noreply.github.com"

          # 繰り返し回数を指定（6回）
          for i in $(seq 1 6); do
            # 新しい変更を作成
            echo $(date) > log.txt

            # 変更をステージしコミット
            git add log.txt
            git commit -m "New commit #$i by GitHub Actions at $(date '+%Y-%m-%dT%H:%M:%S%z')"

            # log.txtには秒までしか出力してないので、1秒以上待たないと変化が出ないのでダメ
            sleep 1.1
          done
      
          # リモートにプッシュ
          git push
