# This is a basic workflow to help you get started with Actions

name: planting

# Controls when the workflow will run
on:
  # Cron job
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "planting"
  planting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Create new change
        run: echo $(date) > log.txt

      # Runs a set of commands using the runners shell
      - name: Create new commit
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add log.txt 
          git commit -m "new commit by github actions" 
          git push
