name: Planting

on:
  # 6時間ごとに実行
  schedule:
    - cron: "0 */6 * * *"
  # webから実行
  workflow_dispatch:

jobs:
  planting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Repeat changes and commits
        run: |
          # Git のユーザー情報設定
          git config user.name  "aazw"
          git config user.email "3594744+aazw@users.noreply.github.com"

          # 繰り返し回数を指定（6回）
          for i in $(seq 1 6); do
            # 新しい変更を作成
            echo $(date) > log.txt

            # 変更をステージしコミット
            git add log.txt
            git commit -m "New commit by GitHub Actions at $(date '+%Y-%m-%dT%H:%M:%S%z')"

            # log.txtには秒までしか出力してないので、1秒以上待たないと変化が出ないのでダメ
            sleep 1.1
          done

          # リモートにプッシュ
          git push
